version: '3.8'
services:
  server:
    build: ./server
    ports:
      - '8080:8080'
  client:
    build: ./client
    network_mode: host
    stdin_open: true
    tty: true
    volumes:
      - ./client:/client
      - /client/node_modules
    depends_on:
      - server
