const addresses = [
  {
    street: '123 University Ave.',
    city: 'San Diego',
    state: 'CA',
    postalCode: '90210',
    country: 'United States',
  },
  {
    street: '245 University St.',
    city: 'San Diego',
    state: 'CA',
    postalCode: '94040',
    country: 'United States',
  },
  {
    street: '431 Broadway Ave.',
    city: 'San Diego',
    state: 'CA',
    postalCode: '92109',
    country: 'United States',
  },
  {
    street: '540 Market St.',
    city: 'San Diego',
    state: 'CA',
    postalCode: '90275',
    country: 'United States',
  },
  {
    street: '632 Broadway Ave.',
    city: 'San Diego',
    state: 'CA',
    postalCode: '94539',
    country: 'United States',
  },
  {
    street: '752 Westheimer Rd.',
    city: 'Houston',
    state: 'TX',
    postalCode: '92028',
    country: 'United States',
  },
  {
    street: '865 Westheimer Rd.',
    city: 'Houston',
    state: 'TX',
    postalCode: '95050',
    country: 'United States',
  },
  {
    street: '936 Westheimer Rd.',
    city: 'Houston',
    state: 'TX',
    postalCode: '94568',
    country: 'United States',
  },
  {
    street: '1043 Richmond Av.',
    city: 'Houston',
    state: 'TX',
    postalCode: '95014',
    country: 'United States',
  },
  {
    street: '1160 Richmond Av.',
    city: 'Houston',
    state: 'TX',
    postalCode: '94544',
    country: 'United States',
  },
  {
    street: '1232 Richmond Av.',
    city: 'Houston',
    state: 'TX',
    postalCode: '95132',
    country: 'United States',
  },
  {
    street: '1315 San Felipe St.',
    city: 'Houston',
    state: 'TX',
    postalCode: '94110',
    country: 'United States',
  },
  {
    street: '1424 San Felipe St.',
    city: 'Houston',
    state: 'TX',
    postalCode: '90036',
    country: 'United States',
  },
  {
    street: '1523 San Felipe St.',
    city: 'Houston',
    state: 'TX',
    postalCode: '90291',
    country: 'United States',
  },
  {
    street: '1642 Bandera Rd.',
    city: 'San Antonio',
    state: 'TX',
    postalCode: '94080',
    country: 'United States',
  },
  {
    street: '1735 Bandera Rd.',
    city: 'San Antonio',
    state: 'TX',
    postalCode: '92646',
    country: 'United States',
  },
  {
    street: '1848 Bandera Rd.',
    city: 'San Antonio',
    state: 'TX',
    postalCode: '94560',
    country: 'United States',
  },
  {
    street: '3012 Broadway St.',
    city: 'San Antonio',
    state: 'TX',
    postalCode: '90265',
    country: 'United States',
  },
  {
    street: '3121 Harry Hines Blv.',
    city: 'Dallas',
    state: 'TX',
    postalCode: '92627',
    country: 'United States',
  },
  {
    street: '3240 Harry Hines Blv.',
    city: 'Dallas',
    state: 'TX',
    postalCode: '93101',
    country: 'United States',
  },
  {
    street: '3333 Ross Av.',
    city: 'Dallas',
    state: 'TX',
    postalCode: '92683',
    country: 'United States',
  },
  {
    street: '3460 Ross Av.',
    city: 'Dallas',
    state: 'TX',
    postalCode: '92083',
    country: 'United States',
  },
  {
    street: '3512 Ross Av.',
    city: 'Dallas',
    state: 'TX',
    postalCode: '94002',
    country: 'United States',
  },
  {
    street: '3630 Cetar Springs Rd.',
    city: 'Dallas',
    state: 'TX',
    postalCode: '95020',
    country: 'United States',
  },
  {
    street: '3713 Cetar Springs Rd.',
    city: 'Dallas',
    state: 'TX',
    postalCode: '95051',
    country: 'United States',
  },
  {
    street: '3840 Cetar Springs Rd.',
    city: 'Dallas',
    state: 'TX',
    postalCode: '95814',
    country: 'United States',
  },
  {
    street: '3945 Cetar Springs Rd.',
    city: 'Dallas',
    state: 'TX',
    postalCode: '92688',
    country: 'United States',
  },
  {
    street: '4050 Cetar Springs Rd.',
    city: 'Dallas',
    state: 'TX',
    postalCode: '90046',
    country: 'United States',
  },
  {
    street: '4132 Cetar Springs Rd.',
    city: 'Dallas',
    state: 'TX',
    postalCode: '94588',
    country: 'United States',
  },
  {
    street: '4240 Greenville Av.',
    city: 'Dallas',
    state: 'TX',
    postalCode: '95823',
    country: 'United States',
  },
  {
    street: '4335 Greenville Av.',
    city: 'Dallas',
    state: 'TX',
    postalCode: '92880',
    country: 'United States',
  },
  {
    street: '4462 Mockingbird Ln.',
    city: 'Dallas',
    state: 'TX',
    postalCode: '90230',
    country: 'United States',
  },
  {
    street: '4555 Riverside Ave.',
    city: 'Jacksonville',
    state: 'FL',
    postalCode: '95008',
    country: 'United States',
  },
  {
    street: '4670 Beack Blv.',
    city: 'Jacksonville',
    state: 'FL',
    postalCode: '92802',
    country: 'United States',
  },
  {
    street: '4752 Riverside Ave.',
    city: 'Jacksonville',
    state: 'FL',
    postalCode: '93003',
    country: 'United States',
  },
  {
    street: '4865 University Blv.',
    city: 'Jacksonville',
    state: 'FL',
    postalCode: '91767',
    country: 'United States',
  },
  {
    street: '4960 Riverside Ave.',
    city: 'Jacksonville',
    state: 'FL',
    postalCode: '94551',
    country: 'United States',
  },
  {
    street: '5090 Atlantic Blv.',
    city: 'Jacksonville',
    state: 'FL',
    postalCode: '94010',
    country: 'United States',
  },
  {
    street: '5156 Atlantic Blv.',
    city: 'Jacksonville',
    state: 'FL',
    postalCode: '92843',
    country: 'United States',
  },
  {
    street: '5265 Atlantic Blv.',
    city: 'Jacksonville',
    state: 'FL',
    postalCode: '92677',
    country: 'United States',
  },
  {
    street: '5350 San Jose Blv.',
    city: 'Jacksonville',
    state: 'FL',
    postalCode: '95824',
    country: 'United States',
  },
  {
    street: '5432 San Jose Blv.',
    city: 'Jacksonville',
    state: 'FL',
    postalCode: '94610',
    country: 'United States',
  },
  {
    street: '5515 Beack Blv.',
    city: 'Jacksonville',
    state: 'FL',
    postalCode: '95131',
    country: 'United States',
  },
  {
    street: '5620 Biscayne Blv.',
    city: 'Miami',
    state: 'FL',
    postalCode: '90250',
    country: 'United States',
  },
  {
    street: '5732 Biscayne Blv.',
    city: 'Miami',
    state: 'FL',
    postalCode: '94568',
    country: 'United States',
  },
  {
    street: '5865 Biscayne Blv.',
    city: 'Miami',
    state: 'FL',
    postalCode: '92806',
    country: 'United States',
  },
  {
    street: '5940 Collins Ave.',
    city: 'Miami',
    state: 'FL',
    postalCode: '95820',
    country: 'United States',
  },
  {
    street: '6062 Collins Ave.',
    city: 'Miami',
    state: 'FL',
    postalCode: '92627',
    country: 'United States',
  },
  {
    street: '6145 Collins Ave.',
    city: 'Miami',
    state: 'FL',
    postalCode: '93619',
    country: 'United States',
  },
  {
    street: '6270 Collins Ave.',
    city: 'Miami',
    state: 'FL',
    postalCode: '94611',
    country: 'United States',
  },
  {
    street: '6355 Ocean Dr.',
    city: 'Miami',
    state: 'FL',
    postalCode: '92647',
    country: 'United States',
  },
  {
    street: '6420 Ocean Dr.',
    city: 'Miami',
    state: 'FL',
    postalCode: '94545',
    country: 'United States',
  },
  {
    street: '6513 Kennedy Blv.',
    city: 'Tampa',
    state: 'FL',
    postalCode: '92545',
    country: 'United States',
  },
  {
    street: '6660 Kennedy Blv.',
    city: 'Tampa',
    state: 'FL',
    postalCode: '92677',
    country: 'United States',
  },
  {
    street: '6745 Fowler Av.',
    city: 'Tampa',
    state: 'FL',
    postalCode: '91321',
    country: 'United States',
  },
  {
    street: '6850 Fowler Av.',
    city: 'Tampa',
    state: 'FL',
    postalCode: '92683',
    country: 'United States',
  },
  {
    street: '6970 Hillsborough Av.',
    city: 'Tampa',
    state: 'FL',
    postalCode: '92646',
    country: 'United States',
  },
  {
    street: '7040 Hillsborough Av.',
    city: 'Tampa',
    state: 'FL',
    postalCode: '92660',
    country: 'United States',
  },
  {
    street: '7165 Hillsborough Av.',
    city: 'Tampa',
    state: 'FL',
    postalCode: '92507',
    country: 'United States',
  },
  {
    street: '7280 Bascom Ave.',
    city: 'San Jose',
    state: 'CA',
    postalCode: '92844',
    country: 'United States',
  },
  {
    street: '7365 Bascom Ave.',
    city: 'San Jose',
    state: 'CA',
    postalCode: '90266',
    country: 'United States',
  },
  {
    street: '7480 Monterey Rd.',
    city: 'San Jose',
    state: 'CA',
    postalCode: '95112',
    country: 'United States',
  },
  {
    street: '7532 Monterey Rd.',
    city: 'San Jose',
    state: 'CA',
    postalCode: '93536',
    country: 'United States',
  },
  {
    street: '7650 King Rd.',
    city: 'San Jose',
    state: 'CA',
    postalCode: '95376',
    country: 'United States',
  },
  {
    street: '7775 King Rd.',
    city: 'San Jose',
    state: 'CA',
    postalCode: '92324',
    country: 'United States',
  },
  {
    street: '7840 King Rd.',
    city: 'San Jose',
    state: 'CA',
    postalCode: '92019',
    country: 'United States',
  },
  {
    street: '7962 McKee Rd.',
    city: 'San Jose',
    state: 'CA',
    postalCode: '92056',
    country: 'United States',
  },
  {
    street: '8025 Kennedy Blv.',
    city: 'Tampa',
    state: 'FL',
    postalCode: '92614',
    country: 'United States',
  },
  {
    street: '8130 Sunset Blv.',
    city: 'Los Angeles',
    state: 'CA',
    postalCode: '92626',
    country: 'United States',
  },
  {
    street: '8240 Santa Monica Blv.',
    city: 'Los Angeles',
    state: 'CA',
    postalCode: '94110',
    country: 'United States',
  },
  {
    street: '8355 Figueroa St.',
    city: 'Los Angeles',
    state: 'CA',
    postalCode: '92543',
    country: 'United States',
  },
  {
    street: '8430 Figueroa St.',
    city: 'Los Angeles',
    state: 'CA',
    postalCode: '95350',
    country: 'United States',
  },
  {
    street: '8525 Wilshire Blv.',
    city: 'Los Angeles',
    state: 'CA',
    postalCode: '93010',
    country: 'United States',
  },
  {
    street: '8640 Wilshire Blv.',
    city: 'Los Angeles',
    state: 'CA',
    postalCode: '95815',
    country: 'United States',
  },
  {
    street: '8762 Wilshire Blv.',
    city: 'Los Angeles',
    state: 'CA',
    postalCode: '91711',
    country: 'United States',
  },
  {
    street: '8855 Sunset Blv.',
    city: 'Los Angeles',
    state: 'CA',
    postalCode: '92111',
    country: 'United States',
  },
  {
    street: '8930 Sunset Blv.',
    city: 'Los Angeles',
    state: 'CA',
    postalCode: '94015',
    country: 'United States',
  },
  {
    street: '9013 Sunset Blv.',
    city: 'Los Angeles',
    state: 'CA',
    postalCode: '93722',
    country: 'United States',
  },
  {
    street: '9120 Market Ave.',
    city: 'San Diego',
    state: 'CA',
    postalCode: '90277',
    country: 'United States',
  },
  {
    street: '9240 Market St.',
    city: 'San Diego',
    state: 'CA',
    postalCode: '95037',
    country: 'United States',
  },
  {
    street: '9355 Balboa Ave.',
    city: 'San Diego',
    state: 'CA',
    postalCode: '91320',
    country: 'United States',
  },
  {
    street: '9440 Rosecrans St.',
    city: 'San Diego',
    state: 'CA',
    postalCode: '94568',
    country: 'United States',
  },
  {
    street: '9555 Harbor Drive',
    city: 'San Diego',
    state: 'CA',
    postalCode: '93030',
    country: 'United States',
  },
];

module.exports = { addresses };
